---
functional:
  - Пользователь должен иметь возможность создать битву
  - Пользователь должен иметь возможность присоединиться к существующей битве битву
  - Пользователь должен иметь возможность выбрать свой язык программирования из списка языков
  - Пользователь должен иметь возможность видеть решение соперника в реальном времени
  - Пользователь должен иметь возможность играть с другим человеком
  - Пользователь должен иметь возможность играть с ботом
  - Пользователь должен иметь возможность общаться с соперником
  - Пользователь должен иметь возможность общаться со зрителями
  - Пользователь должен иметь возможность видеть результаты запуска тестов
  - Пользователь должен иметь возможность видеть сообщение о победе
  - Пользователь должен иметь возможность видеть сообщение о проигрыше
  - Пользователь должен иметь возможность присоединиться к существующим турнирам
  - Пользователь должен иметь возможность видеть список участников в онлайне
  - Пользователь должен иметь возможность писать в общий чат для всех участников
  - Пользователь должен иметь возможность создать свой турнир
  - Пользователь должен иметь возможность видеть правила турниров
  - Пользователь должен иметь возможность присоединиться к существующему клану участников
  - Пользователь должен иметь возможность создать новый клан участников
  - Пользователь должен иметь возможность управлять своим профилем
  - Пользователь должен иметь возможность видеть рейтинг участников
  - Пользователь должен иметь возможность видеть существующие задачи
  - Пользователь должен иметь возможность добавить новую задачу
  - Пользователь должен иметь возможность выбрать тип звука
  - Пользователь должен иметь возможность уровень звука
  - Пользователь должен иметь возможность выбрать язык между русским и английским
  - Пользователь должен иметь возможность присоединиться к социальным сетям комьюнити
  - Пользователь должен иметь возможность видеть календарь с турнирами
  - Пользователь должен иметь возможность видеть свой elo рейтинг
  - Пользователь должен иметь возможность видеть своё место в рейтинге
  - Пользователь должен иметь возможность видетьколичество заработанных баллов
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Сайт не должен перезагружать страницу, когда пользователь переходит по разным разделам
  - Битва должна храниться в сессии браузера
implicit:
  - Пользователь должен иметь возможность выйти из начатой битвы
  - Пользователь должен иметь возможность перейти по ссылке на репозиторий проекта
  - Пользователь должен иметь возможность поставить звезду репозиторуию на гитхабе
  - Пользователь должен иметь возможность видеть список кланов
  - Пользователь должен иметь возможность видеть описание клана
  - Пользователь должен иметь возможность видеть аватарку из гитхаба или заглушку
